apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.data.name }}-secret
  namespace: {{ .Values.data.namespace }}
type: Opaque
data:
  secret-1: {{ randAlphaNum 32 | b64enc | quote }}
  secret-2: {{ randAlphaNum 24 | b64enc | quote }}
  secret-3: {{ randAlphaNum 16 | b64enc | quote }}
